### ISSUE TITLE
How to load messages like whatsapp when we scroll to top. Please add this feature

### ISSUE THREAD

**Issue by sudhanshu077** [rajayogan/ionic3chat#1]
In chat app, we do not load all msg of user. we load few msgs. when the user scroll to top then we load all msgs.

**Comment by rajayogan** [comment]
I have done this already bro.. I think what you mean is to scroll to the latest message received when the chat is started or whenever a new message is received in the current chat window. I will be making a post on that in the later parts of this series and then committing the code in this repo. This is still a work in progress. Thanks.
