### ISSUE TITLE
group chat and image sending feature

### ISSUE THREAD

**Issue by cquezpro** [rajayogan/ionic3chat#2]
Hi @rajayogan 
How are you doing?
I am very interested in this chat app.
I saw your video.
https://www.youtube.com/watch?v=sOnypxX-Ewk

This video has group chat and image sending feature, but I can't find those feature on this repo.
Could you commit those features?
Thank you
Sincerely
Sirius

**Comment by rajayogan** [comment]
Hello sir,
     This is a series of videos on youtube.. I commit the code every time I upload a new episode on youtube.. So the above features will be pushed as and when the videos are done..

Thanks,
Raja

**Comment by cquezpro** [comment]
Hi @rajayogan 
Thanks for your reply.
I appreciate about this.
and could you let me know when you will post group chat feature?

Best regards
@Sirius

**Comment by rajayogan** [comment]
To understand group chat, one must understand the concept of mesh networks. The next episode will be on sending images in chat.. After that a video on mesh networks. After that creating groups, adding members to groups, sending messages.. and so on.. (In short, there will be atleast 4 or more episodes)
