### ISSUE TITLE
Cannot make build

### ISSUE THREAD

**Issue by rajat-g** [rajayogan/ionic3chat#3]
While running this command i get this error
ionic cordova build android --prod --release

Error: ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../angularfire2/auth' in 'D:\Yash Tech Workplace\Ionic Workplace\mychatapp\src\app'
resolve '../../angularfire2/auth' in 'D:\Yash Tech Workplace\Ionic Workplace\mychatapp\src\app'
  using description file: D:\Yash Tech Workplace\Ionic Workplace\mychatapp\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Yash Tech Workplace\Ionic Workplace\mychatapp\package.json (relative path: ./src/app)
    using description file: D:\Yash Tech Workplace\Ionic Workplace\mychatapp\package.json (relative path: ./angularfire2/auth)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth.ts doesn't exist
      as directory
        D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth doesn't exist
[D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth]
[D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth.js]
[D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth.ts]
[D:\Yash Tech Workplace\Ionic Workplace\mychatapp\angularfire2\auth]
 @ ./src/app/app.module.ngfactory.js 49:0-52
 @ ./src/app/main.ts

**Comment by rajayogan** [comment]
Kindly check whether you have installed angularfire2 in your project. Thanks.

**Comment by rajat-g** [comment]
I have installed angularfire2. its running fine in development mode but as soon as I start making production build it gives above error.
