### ISSUE TITLE
"ionic serve" doesn't work

### ISSUE THREAD

**Issue by inejose** [rajayogan/ionic3chat#5]
Hi,

when I try to: `ionic serve` there is an error:

Cannot find module: 'path/to/the/project/node_modules/@ionic/app-scripts

how can I fix it?

Thanks and thanks for the app

**Comment by rajayogan** [comment]
Try giving npm install in the project directory (from your terminal / command prompt) then try this command.. Also, I would highly recommend you to run it on a device.. Thanks.
